"""empty message

Revision ID: 19f39723f59f
Revises: f8920d0078aa
Create Date: 2022-07-04 10:53:15.241094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19f39723f59f'
down_revision = 'f8920d0078aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_users')
    op.add_column('dateformat', sa.Column('desc', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dateformat', 'desc')
    
    # ### end Alembic commands ###
