"""empty message

Revision ID: 2202ae3cbf1b
Revises: 
Create Date: 2022-07-03 17:09:12.098587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2202ae3cbf1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_details', 'val_date_col',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bank_details', 'txn_date_col',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bank_details', 'chq_no_col',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bank_details', 'txn_rmrk_col',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bank_details', 'with_amt_col',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bank_details', 'crdt_amt_col',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bank_details', 'bal_col',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_details', 'bal_col',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bank_details', 'crdt_amt_col',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bank_details', 'with_amt_col',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bank_details', 'txn_rmrk_col',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bank_details', 'chq_no_col',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bank_details', 'txn_date_col',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bank_details', 'val_date_col',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
