"""Adding password reset hash info

Revision ID: 598d5a284e00
Revises: 785dcd47aea8
Create Date: 2023-08-08 18:38:16.220124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598d5a284e00'
down_revision = '785dcd47aea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accountholder', sa.Column('reset_hash', sa.String(length=200), nullable=True))
    op.add_column('accountholder', sa.Column('reset_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accountholder', 'reset_expiry')
    op.drop_column('accountholder', 'reset_hash')
    # ### end Alembic commands ###
