"""empty message

Revision ID: 5c5f10f47e94
Revises: 9b93be81c028
Create Date: 2024-02-06 19:01:13.341810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5f10f47e94'
down_revision = '9b93be81c028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accountholder', sa.Column('last_logged_in', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accountholder', 'last_logged_in')
    # ### end Alembic commands ###
