"""empty message

Revision ID: 785dcd47aea8
Revises: 
Create Date: 2022-07-11 13:23:59.530921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785dcd47aea8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountholder',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('email_id', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('u_active', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_table('dateformat',
    sa.Column('date_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('desc', sa.String(length=200), nullable=False),
    sa.Column('py_date', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('date_id'),
    sa.UniqueConstraint('date_format')
    )
    op.create_table('bank_details',
    sa.Column('bank_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('start_row', sa.Integer(), nullable=True),
    sa.Column('val_date_col', sa.Integer(), nullable=True),
    sa.Column('txn_date_col', sa.Integer(), nullable=True),
    sa.Column('chq_no_col', sa.Integer(), nullable=True),
    sa.Column('txn_rmrk_col', sa.Integer(), nullable=True),
    sa.Column('with_amt_col', sa.Integer(), nullable=True),
    sa.Column('crdt_amt_col', sa.Integer(), nullable=True),
    sa.Column('bal_col', sa.Integer(), nullable=True),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['dateformat.date_id'], ),
    sa.PrimaryKeyConstraint('bank_id'),
    sa.UniqueConstraint('bank_name')
    )
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_no', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('joint', sa.Boolean(), nullable=True),
    sa.Column('bank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank'], ['bank_details.bank_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_no')
    )
    op.create_table('acc_transaction',
    sa.Column('txn_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value_date', sa.DateTime(), nullable=False),
    sa.Column('txn_date', sa.DateTime(), nullable=False),
    sa.Column('txn_remarks', sa.Text(), nullable=False),
    sa.Column('cheque_no', sa.String(length=20), nullable=True),
    sa.Column('withdrawal_amt', sa.Float(), nullable=True),
    sa.Column('deposit_amt', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('acc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acc_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('txn_id'),
    sa.UniqueConstraint('value_date', 'txn_date', 'txn_remarks', 'withdrawal_amt', 'deposit_amt', 'balance', 'cheque_no', name='unique_txn')
    )
    op.create_table('account_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accountholder.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_users')
    op.drop_table('acc_transaction')
    op.drop_table('account')
    op.drop_table('bank_details')
    op.drop_table('dateformat')
    op.drop_table('accountholder')
    # ### end Alembic commands ###
