"""empty message

Revision ID: 9b93be81c028
Revises: 598d5a284e00
Create Date: 2023-12-02 11:40:42.656866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b93be81c028'
down_revision = '598d5a284e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acc_transaction', sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('account', sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('account', sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True))
    op.add_column('accountholder', sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('accountholder', sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bank_details', sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('bank_details', sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True))
    op.add_column('dateformat', sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('dateformat', sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dateformat', 'updated_on')
    op.drop_column('dateformat', 'created_on')
    op.drop_column('bank_details', 'updated_on')
    op.drop_column('bank_details', 'created_on')
    op.drop_column('accountholder', 'updated_on')
    op.drop_column('accountholder', 'created_on')
    op.drop_column('account', 'updated_on')
    op.drop_column('account', 'created_on')
    op.drop_column('acc_transaction', 'created_on')
    # ### end Alembic commands ###
