"""empty message

Revision ID: e9c83f9b0d01
Revises: 19f39723f59f
Create Date: 2022-07-04 18:01:05.588046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9c83f9b0d01'
down_revision = '19f39723f59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_txn', 'acc_transaction', ['value_date', 'txn_date', 'txn_remarks', 'withdrawal_amt', 'deposit_amt', 'balance', 'cheque_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_txn', 'acc_transaction', type_='unique')
    
    # ### end Alembic commands ###
