"""empty message

Revision ID: f8920d0078aa
Revises: 2202ae3cbf1b
Create Date: 2022-07-03 17:31:53.096683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8920d0078aa'
down_revision = '2202ae3cbf1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dateformat',
    sa.Column('date_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('py_date', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('date_id'),
    sa.UniqueConstraint('date_format')
    )

    op.add_column('bank_details', sa.Column('date_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bank_details', 'dateformat', ['date_id'], ['date_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_details', type_='foreignkey')
    op.drop_column('bank_details', 'date_id')

    op.drop_table('dateformat')
    # ### end Alembic commands ###
